---
title: "00 - preparation"
author: "Martin Proks"
date: '`r Sys.Date()`'
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_format='all',
                        output_dir='../reports/')})
output:
  # To create PDF report, uncomment below
  # pdf_document:
  #   toc: yes
  html_document:
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float: yes
    df_print: paged
    dev: png
---

```{r knitr, include = FALSE}
DOCNAME = knitr::current_input()
knitr::opts_chunk$set(autodep        = TRUE,
                      cache          = FALSE,
                      cache.path     = paste0("cache/", DOCNAME, "/"),
                      cache.comments = TRUE,
                      echo           = TRUE,
                      error          = FALSE,
                      fig.align      = "center",
                      fig.path       = paste0("../reports/figures/", DOCNAME, "/"),
                      fig.width      = 10,
                      fig.height     = 8,
                      message        = FALSE,
                      warning        = FALSE)
```

# Find count matrix

```{r}
files <- stringr::str_sort(list.files(path = '../GEO/', pattern = "^AB", full.names = T), numeric = T)
```

# Concatenate counts

```{r}
counts <- data.frame(read.table(files[1], sep = "\t"))
for (i in 2:length(files)) {
  counts <- cbind(counts, read.table(files[i], sep = "\t"))
}

rownames(counts) <- unlist(lapply(rownames(counts), FUN = function(x) { return(strsplit(x, ';')[[1]][1]) }))
```

# Save counts

```{r}
data <- NULL
data$counts <- counts
data$metadata <- as.data.frame(readxl::read_excel("../data/corrected_fung_design_file.xlsx", sheet = "Sheet1", col_names = T)[-1])
data$annot <- read.table("../data/gene-annotations.tsv", sep = "\t", header = T)
rownames(data$metadata) <- data$metadata[,1]

saveRDS(data, file = "../data/processed/MARS-Fung.RDS")
```

# Session info

```{r}
sessionInfo()
```
